#!/bin/bash
##SBATCH --exclusive
#SBATCH --array=1-88 ## single calculation to run in current folder so no need to change.
#SBATCH --mail-type=None
#SBATCH --mem-per-cpu=3800
#SBATCH -A project01915 
#SBATCH -C avx512
#SBATCH -J MTP_active
#SBATCH -e err/red_final_%A_%a
#SBATCH -n 1
#SBATCH -o out/red_final_%A_%a
#SBATCH -t 00:30:00
#Generated by HPCtools_v2.csubmit.Submit

#---------------
module purge
module use /home/groups/da_mm/modules
export MM_APPS_ROOT=/home/groups/da_mm/apps
export MM_MODULES_ROOT=/home/groups/da_mm/modules


## Collect reduced structures from individual subdirs and reduce furhter
## !!! Make sure that you specify the right potential / training DB !!!                                                                                                                                    


module load mlip
unset I_MPI_PMI_LIBRARY

cat  */C-add_to_train.cfg > B-preselected.cfg
srun mlp select-add ../mtp_fit/BTO_0.mtp ../mtp_fit/dft_0.cfg B-preselected.cfg C-add_to_train.cfg
