#!/bin/bash
#SBATCH --exclusive
#SBATCH --mail-type=ALL
#SBATCH --mem-per-cpu=3800
#SBATCH -A project01915
#SBATCH -C avx512
#SBATCH -J test
#SBATCH -e err.%j
#SBATCH -n 1
#SBATCH -o out.%j
#SBATCH --time=00:30:00
#Generated by HPCtools.csubmit.Submit


mpiexec -n 1 ~/miniconda3/bin/gpaw python raman_plot.py
# module purge
# module use /home/groups/da_mm/modules
# unset I_MPI_PMI_LIBRARY
# export MM_APPS_ROOT=/home/groups/da_mm/apps
# export MM_MODULES_ROOT=/home/groups/da_mm/modules

# module --ignore-cache load gpaw_intel2020/21.6.0

# srun gpaw python supercell_matrix.py
